### ISSUE TITLE
💻[ToDo] FE : New Design

### ISSUE THREAD

**Issue by junny1995** [codestates-seb/seb40_main_024#100]
##  INFO
* Front_End
* Commit Type : design
* Detail : 로그인, 회원가입, 임시비밀번호, 자산공유 커뮤니티, 자유게시판 css 수정

## TODO
- [x] 로그인 페이지 box, input, button css 재수정
- [x] 로그인 페이지 box, input, button css 재수정
- [x] 로그인 페이지 box, input, button css 재수정
- [x] 자산공유 커뮤니티 게시글 리스트, 전체 사이즈 재조절, 검색박스 추가
- [x] 자산공유 커뮤니티 게시글 리스트, 전체 사이즈 재조절, 검색박스 추가
