### ISSUE TITLE
💻[ToDo] BE : CORS 수정중

### ISSUE THREAD

**Issue by codinginfant** [codestates-seb/seb40_main_024#123]
##  INFO
* Back_End
* Commit Type : feat
* Detail : CORS 에러 수정. 아직 진행중입니다

## TODO
- [ ] ec2 인스턴스 생성
- [ ] 깃 허브 merge conflict 해결 및 PR
- [ ] CORS 에러 수정
