### ISSUE TITLE
💻[ToDo] BE : RDS 연결, Asset -> CVS 파일 작성

### ISSUE THREAD

**Issue by codinginfant** [codestates-seb/seb40_main_024#136]
##  INFO
* Back_End
* Commit Type : feat
* Detail :  RDS 연결, Asset -> CVS 파일 작성

## TODO
- [x] EC2에 RDS 연결
- [x] RDS 설정 변경
- [x] mysql로 연결 확인하기
- [ ] application.yml 설정 변경
- [ ] Asset 추가 기능 생성 (asset별 적용 가능한 dto, controller 등 수정)
- [ ] CVS 생성 파일 작성
