### ISSUE TITLE
💻[ToDo] FE : comment 통신

### ISSUE THREAD

**Issue by jioneee** [codestates-seb/seb40_main_024#163]
##  INFO
* Front_End
* Commit Type : feat
* Detail : 댓글 통신 구현

- [x] get 댓글 조회
- [x]  post 댓글 등록
- [ ] patch 댓글 수정
- [x] delete 댓글 삭제
