### ISSUE TITLE
💻[ToDo] BE : week 1 - 게시판, 댓글, 목표 자산

### ISSUE THREAD

**Issue by JadeMK** [codestates-seb/seb40_main_024#93]
##  INFO
* Back_End
* Commit Type : feat, fix
* Detail : week 1 구현 내역

## TODO
- [X] 게시판 구현 (CRUD & 좋아요)
- [X] 댓글 구현 (CRUD)
- [X] 목표 자산 구현 (CRUD & 성취도)
- [X] 게시판, 댓글 매핑
