### ISSUE TITLE
💻[ToDo] BE : 프론트단과 통신을 위한 cors 설정

### ISSUE THREAD

**Issue by JadeMK** [codestates-seb/seb40_main_024#94]
##  INFO
* Back_End
* Commit Type : fix
* Detail : CORS 에러 핸들링을 위한 설정

## TODO
- [X] CorsConfigurationSource 이용, Security filter chain 을 사용한 설정 시도
- [X] WebMvcConfigurer 상속 클래스 이용, 다양한 cors 설정 시도
- [ ] cors 에러 핸들링 😞
